@startuml
skinparam shadowing false
hide members
hide circle
class "L.L"
class "L.C"

class "R.L"
class "R.D"
class "R.C"

class "Type.List"
class "Type.Card"

class "G.L"
class "G.M"
class "G.C"

class "G'.L"
class "G'.M"
class "G'.C"
class "G'.D"

"L.L" --> "L.C" : "cards"

"R.L" --> "R.C" : "cards"
"R.L" --> "R.D" : "cards"

"G.L" --> "G.C" : "cards"

"G'.L" --> "G'.C" : "cards"
"G'.L" --> "G'.D" : "cards"

"Type.List" --> "Type.Card" : "cards"

"L.L" --> "R.L" : "r"
"L.C" --> "R.C" : "r"

"L.L" --> "G.L" : "m"
"L.C" --> "G.C" : "m"

"G.L" --> "G'.L" : "r'"
"G.M" --> "G'.M" : "r'"
"G.C" --> "G'.C" : "r'"

"R.L" --> "G'.L" : "m'"
"R.C" --> "G'.C" : "m'"
"R.D" --> "G'.D" : "m'"

"L.L" --> "Type.List" : "type_L"
"R.L" --> "Type.List" : "type_R"
"G.L" --> "Type.List" : "type_G"
"G'.L" --> "Type.List" : "type_G'"

"L.C" --> "Type.Card" : "type_L"
"R.C" --> "Type.Card" : "type_R"
"R.D" --> "Type.Card" : "type_R"
"G.C" --> "Type.Card" : "type_G"
"G'.C" --> "Type.Card" : "type_G'"
"G'.D" --> "Type.Card" : "type_G'"

@enduml