@startuml
skinparam shadowing false
hide members
hide circle
class "L.Board"
class "L.J : List"
"L.Board"-->"L.J : List" : "lists"
class "R.Board"
class "R.J : List"
class "R.X : Card"
"R.Board"-->"R.J : List" : "lists"
"R.J : List"-->"R.X : Card" : "cards"
class "G.Board"
class "G.i : List"
class "G.j : List"
class "G.x : Card"
class "G.k : List"
class "G.y : Card"
"G.Board"-->"G.i : List" : "lists"
"G.Board"-->"G.j : List" : "lists"
"G.Board"-->"G.k : List" : "lists"
"G.j : List"-->"G.i : List" : "previous"
"G.j : List"-->"G.k : List" : "next"
"G.j : List"-->"G.x : Card" : "cards"
"G.k : List"-->"G.y : Card" : "cards"
class "r;vert==m;horiz.Board"
class "r;vert==m;horiz.i : List"
class "r;vert==m;horiz.j : List"
class "r;vert==m;horiz.x : Card"
class "r;vert==m;horiz.k : List"
class "r;vert==m;horiz.y : Card"
class "r;vert==m;horiz.X : Card"
"r;vert==m;horiz.Board"-->"r;vert==m;horiz.i : List" : "lists"
"r;vert==m;horiz.Board"-->"r;vert==m;horiz.j : List" : "lists"
"r;vert==m;horiz.Board"-->"r;vert==m;horiz.k : List" : "lists"
"r;vert==m;horiz.j : List"-->"r;vert==m;horiz.i : List" : "previous"
"r;vert==m;horiz.j : List"-->"r;vert==m;horiz.k : List" : "next"
"r;vert==m;horiz.j : List"-->"r;vert==m;horiz.x : Card" : "cards"
"r;vert==m;horiz.k : List"-->"r;vert==m;horiz.y : Card" : "cards"
"r;vert==m;horiz.j : List"-->"r;vert==m;horiz.X : Card" : "cards"
"L.Board" --> "R.Board" : "r"
"L.J : List" --> "R.J : List" : "r"
"L.Board" --> "G.Board" : "m"
"L.J : List" --> "G.j : List" : "m"
"G.Board" --> "r;vert==m;horiz.Board" : "horiz;r;vert==m;horiz"
"G.i : List" --> "r;vert==m;horiz.i : List" : "horiz;r;vert==m;horiz"
"G.j : List" --> "r;vert==m;horiz.j : List" : "horiz;r;vert==m;horiz"
"G.x : Card" --> "r;vert==m;horiz.x : Card" : "horiz;r;vert==m;horiz"
"G.k : List" --> "r;vert==m;horiz.k : List" : "horiz;r;vert==m;horiz"
"G.y : Card" --> "r;vert==m;horiz.y : Card" : "horiz;r;vert==m;horiz"
"R.Board" --> "r;vert==m;horiz.Board" : "vert;r;vert==m;horiz"
"R.J : List" --> "r;vert==m;horiz.j : List" : "vert;r;vert==m;horiz"
"R.X : Card" --> "r;vert==m;horiz.X : Card" : "vert;r;vert==m;horiz"
@enduml
