@startuml
skinparam shadowing false
hide members
hide circle
class "SimpleTrello.List"
class "SimpleTrello.Card"
class "SimpleTrello.Board"
"SimpleTrello.List"-->"SimpleTrello.List" : "previous"
"SimpleTrello.List"-->"SimpleTrello.List" : "next"
"SimpleTrello.List"-->"SimpleTrello.Card" : "cards"
"SimpleTrello.Board"-->"SimpleTrello.List" : "lists"
@enduml
