@startuml
skinparam shadowing false
hide members
hide circle
class "L.Board"
class "L.L : List"
class "L.C : Card"
class "L.L_ : List"
"L.Board"-->"L.L : List" : "lists"
"L.Board"-->"L.L_ : List" : "lists"
"L.L : List"-->"L.L_ : List" : "next"
"L.L : List"-->"L.C : Card" : "cards"
class "K.Board"
class "K.L : List"
class "K.L_ : List"
class "K.C : Card"
"K.Board"-->"K.L : List" : "lists"
"K.Board"-->"K.L_ : List" : "lists"
"K.L : List"-->"K.L_ : List" : "next"
class "R.Board"
class "R.L : List"
class "R.L_ : List"
class "R.C : Card"
"R.Board"-->"R.L : List" : "lists"
"R.Board"-->"R.L_ : List" : "lists"
"R.L : List"-->"R.L_ : List" : "next"
"R.L_ : List"-->"R.C : Card" : "cards"
class "G.Board"
class "G.i : List"
class "G.j : List"
class "G.x : Card"
class "G.k : List"
class "G.y : Card"
"G.Board"-->"G.i : List" : "lists"
"G.Board"-->"G.j : List" : "lists"
"G.Board"-->"G.k : List" : "lists"
"G.j : List"-->"G.i : List" : "previous"
"G.j : List"-->"G.k : List" : "next"
"G.j : List"-->"G.x : Card" : "cards"
"G.k : List"-->"G.y : Card" : "cards"
class "D.i : List"
class "D.y : Card"
class "D.Board"
class "D.j : List"
class "D.k : List"
class "D.x : Card"
"D.Board"-->"D.i : List" : "lists"
"D.j : List"-->"D.i : List" : "previous"
"D.k : List"-->"D.y : Card" : "cards"
"D.j : List"-->"D.k : List" : "next"
"D.Board"-->"D.j : List" : "lists"
"D.Board"-->"D.k : List" : "lists"
class "m;right==d;left.i : List"
class "m;right==d;left.y : Card"
class "m;right==d;left.Board"
class "m;right==d;left.j : List"
class "m;right==d;left.k : List"
class "m;right==d;left.x : Card"
"m;right==d;left.Board"-->"m;right==d;left.i : List" : "lists"
"m;right==d;left.j : List"-->"m;right==d;left.i : List" : "previous"
"m;right==d;left.k : List"-->"m;right==d;left.y : Card" : "cards"
"m;right==d;left.j : List"-->"m;right==d;left.k : List" : "next"
"m;right==d;left.Board"-->"m;right==d;left.j : List" : "lists"
"m;right==d;left.Board"-->"m;right==d;left.k : List" : "lists"
"m;right==d;left.k : List"-->"m;right==d;left.x : Card" : "cards"
"K.Board" --> "L.Board" : "m"
"K.L : List" --> "L.L : List" : "m"
"K.L_ : List" --> "L.L_ : List" : "m"
"K.C : Card" --> "L.C : Card" : "m"
"K.Board" --> "R.Board" : "m"
"K.L : List" --> "R.L : List" : "m"
"K.L_ : List" --> "R.L_ : List" : "m"
"K.C : Card" --> "R.C : Card" : "m"
"L.Board" --> "G.Board" : "m"
"L.L : List" --> "G.j : List" : "m"
"L.C : Card" --> "G.x : Card" : "m"
"L.L_ : List" --> "G.k : List" : "m"
"K.Board" --> "D.Board" : "d"
"K.L : List" --> "D.j : List" : "d"
"K.L_ : List" --> "D.k : List" : "d"
"K.C : Card" --> "D.x : Card" : "d"
"D.i : List" --> "G.i : List" : "l'"
"D.y : Card" --> "G.y : Card" : "l'"
"D.Board" --> "G.Board" : "l'"
"D.j : List" --> "G.j : List" : "l'"
"D.k : List" --> "G.k : List" : "l'"
"D.x : Card" --> "G.x : Card" : "l'"
"D.i : List" --> "m;right==d;left.i : List" : "left;m;right==d;left"
"D.y : Card" --> "m;right==d;left.y : Card" : "left;m;right==d;left"
"D.Board" --> "m;right==d;left.Board" : "left;m;right==d;left"
"D.j : List" --> "m;right==d;left.j : List" : "left;m;right==d;left"
"D.k : List" --> "m;right==d;left.k : List" : "left;m;right==d;left"
"D.x : Card" --> "m;right==d;left.x : Card" : "left;m;right==d;left"
"R.Board" --> "m;right==d;left.Board" : "right;m;right==d;left"
"R.L : List" --> "m;right==d;left.j : List" : "right;m;right==d;left"
"R.L_ : List" --> "m;right==d;left.k : List" : "right;m;right==d;left"
"R.C : Card" --> "m;right==d;left.x : Card" : "right;m;right==d;left"
@enduml
