@startuml
skinparam shadowing false
hide members
hide circle
class "L.C"
class "G.Board"
class "G.i : List"
class "G.j : List"
class "G.x : Card"
class "G.k : List"
class "G.y : Card"
"G.Board"-->"G.i : List" : "lists"
"G.Board"-->"G.j : List" : "lists"
"G.Board"-->"G.k : List" : "lists"
"G.j : List"-->"G.i : List" : "previous"
"G.j : List"-->"G.x : Card" : "cards"
"G.j : List"-->"G.k : List" : "next"
"G.k : List"-->"G.y : Card" : "cards"
class "G_.Board"
class "G_.i : List"
class "G_.j : List"
class "G_.x : Card"
class "G_.k : List"
class "G_.y : Card"
"G_.Board"-->"G_.i : List" : "lists"
"G_.Board"-->"G_.j : List" : "lists"
"G_.Board"-->"G_.k : List" : "lists"
"G_.j : List"-->"G_.i : List" : "previous"
"G_.j : List"-->"G_.x : Card" : "cards"
"G_.j : List"-->"G_.k : List" : "next"
class "D.Board"
class "D.i : List"
class "D.j : List"
class "D.x : Card"
class "D.k : List"
"D.Board"-->"D.i : List" : "lists"
"D.Board"-->"D.j : List" : "lists"
"D.Board"-->"D.k : List" : "lists"
"D.j : List"-->"D.i : List" : "previous"
"D.j : List"-->"D.x : Card" : "cards"
"D.j : List"-->"D.k : List" : "next"
class "initial_EMPTY_GRAPH;right==d;left.Board"
class "initial_EMPTY_GRAPH;right==d;left.i : List"
class "initial_EMPTY_GRAPH;right==d;left.j : List"
class "initial_EMPTY_GRAPH;right==d;left.x : Card"
class "initial_EMPTY_GRAPH;right==d;left.k : List"
"initial_EMPTY_GRAPH;right==d;left.Board"-->"initial_EMPTY_GRAPH;right==d;left.i : List" : "lists"
"initial_EMPTY_GRAPH;right==d;left.Board"-->"initial_EMPTY_GRAPH;right==d;left.j : List" : "lists"
"initial_EMPTY_GRAPH;right==d;left.Board"-->"initial_EMPTY_GRAPH;right==d;left.k : List" : "lists"
"initial_EMPTY_GRAPH;right==d;left.j : List"-->"initial_EMPTY_GRAPH;right==d;left.i : List" : "previous"
"initial_EMPTY_GRAPH;right==d;left.j : List"-->"initial_EMPTY_GRAPH;right==d;left.x : Card" : "cards"
"initial_EMPTY_GRAPH;right==d;left.j : List"-->"initial_EMPTY_GRAPH;right==d;left.k : List" : "next"
"L.C" --> "G.y : Card" : "m"
"L.C" --> "G_.y : Card" : "_m_"
"G_.Board" --> "G.Board" : "_g_"
"G_.i : List" --> "G.i : List" : "_g_"
"G_.j : List" --> "G.j : List" : "_g_"
"G_.x : Card" --> "G.x : Card" : "_g_"
"G_.k : List" --> "G.k : List" : "_g_"
"G_.y : Card" --> "G.y : Card" : "_g_"
"D.Board" --> "G_.Board" : "l'"
"D.i : List" --> "G_.i : List" : "l'"
"D.j : List" --> "G_.j : List" : "l'"
"D.x : Card" --> "G_.x : Card" : "l'"
"D.k : List" --> "G_.k : List" : "l'"
"D.Board" --> "initial_EMPTY_GRAPH;right==d;left.Board" : "left;initial_EMPTY_GRAPH;right==d;left"
"D.i : List" --> "initial_EMPTY_GRAPH;right==d;left.i : List" : "left;initial_EMPTY_GRAPH;right==d;left"
"D.j : List" --> "initial_EMPTY_GRAPH;right==d;left.j : List" : "left;initial_EMPTY_GRAPH;right==d;left"
"D.x : Card" --> "initial_EMPTY_GRAPH;right==d;left.x : Card" : "left;initial_EMPTY_GRAPH;right==d;left"
"D.k : List" --> "initial_EMPTY_GRAPH;right==d;left.k : List" : "left;initial_EMPTY_GRAPH;right==d;left"
@enduml
