@startuml
skinparam shadowing false
hide members
hide circle
class "L.Board"
class "L.J : List"
"L.Board"-->"L.J : List" : "lists"
class "P.Board"
class "P.J : List"
class "P.X : Card"
"P.Board"-->"P.J : List" : "lists"
"P.J : List"-->"P.X : Card" : "cards"
class "C1.Board"
class "C1.J : List"
class "C1.X : Card"
class "C1.K : List"
"C1.Board"-->"C1.J : List" : "lists"
"C1.Board"-->"C1.K : List" : "lists"
"C1.J : List"-->"C1.X : Card" : "cards"
"C1.J : List"-->"C1.K : List" : "previous"
class "C2.Board"
class "C2.J : List"
class "C2.X : Card"
class "C2.K : List"
"C2.Board"-->"C2.J : List" : "lists"
"C2.Board"-->"C2.K : List" : "lists"
"C2.J : List"-->"C2.X : Card" : "cards"
"C2.J : List"-->"C2.K : List" : "next"
"L.Board" --> "P.Board" : "p"
"L.J : List" --> "P.J : List" : "p"
"P.Board" --> "C1.Board" : "c1"
"P.J : List" --> "C1.J : List" : "c1"
"P.X : Card" --> "C1.X : Card" : "c1"
"P.Board" --> "C2.Board" : "c2"
"P.J : List" --> "C2.J : List" : "c2"
"P.X : Card" --> "C2.X : Card" : "c2"
@enduml
