@startuml
digraph Diagram {
  "L:TG_L";
  "P:TG_P";
  "C1:TG_C1";
  "C2:TG_C2";
  "L:TG_L"->"P:TG_P" [label=" p"];
  "P:TG_P"->"C1:TG_C1" [label=" c1"];
  "P:TG_P"->"C2:TG_C2" [label=" c2"];
}
@enduml
