@startuml
skinparam shadowing false
hide members
hide circle
class "L.Board"
class "L.J : List"
"L.Board"-->"L.J : List" : "lists"
class "G.Board"
class "G.i : List"
class "G.j : List"
class "G.x : Card"
class "G.k : List"
class "G.y : Card"
"G.Board"-->"G.i : List" : "lists"
"G.Board"-->"G.j : List" : "lists"
"G.Board"-->"G.k : List" : "lists"
"G.j : List"-->"G.x : Card" : "cards"
"G.j : List"-->"G.i : List" : "previous"
"G.j : List"-->"G.k : List" : "next"
"G.k : List"-->"G.y : Card" : "cards"
"L.Board" --> "G.Board" : "m"
"L.J : List" --> "G.j : List" : "m"
@enduml
