@startuml
skinparam shadowing false
hide members
hide circle
class "G:TG.L : List"
class "G:TG.C : Card"
"G:TG.L : List"-->"G:TG.C : Card" : "cards"
class "G':TG.i : List"
class "G':TG.j : List"
class "G':TG.k : List"
class "G':TG.x : Card"
class "G':TG.y : Card"
"G':TG.j : List"-->"G':TG.i : List" : "prev"
"G':TG.j : List"-->"G':TG.k : List" : "next"
"G':TG.j : List"-->"G':TG.x : Card" : "e1:cards"
"G':TG.k : List"-->"G':TG.y : Card" : "e2:cards"

"G:TG.L : List" --> "G':TG.k : List" : "m"
"G:TG.C : Card" --> "G':TG.y : Card" : "m"
@enduml
