@startuml
skinparam shadowing false
hide members
hide circle
class "G.Board"
class "G.i : List"
class "G.j : List"
class "G.x : Card"
class "G.k : List"
class "G.y : Card"
"G.Board"-->"G.i : List" : "lists"
"G.Board"-->"G.j : List" : "lists"
"G.Board"-->"G.k : List" : "lists"
"G.j : List"-->"G.x : Card" : "cards"
"G.j : List"-->"G.i : List" : "previous"
"G.j : List"-->"G.k : List" : "next"
"G.k : List"-->"G.y : Card" : "cards"
class "TG_G.List"
class "TG_G.Card"
class "TG_G.Board"
"TG_G.List"-->"TG_G.List" : "previous"
"TG_G.List"-->"TG_G.List" : "next"
"TG_G.List"-->"TG_G.Card" : "cards"
"TG_G.Board"-->"TG_G.List" : "lists"
class "Ecore.EClass"
"Ecore.EClass"-->"Ecore.EClass" : "EReference"
"G.Board" --> "TG_G.Board" : "type_G"
"G.i : List" --> "TG_G.List" : "type_G"
"G.j : List" --> "TG_G.List" : "type_G"
"G.x : Card" --> "TG_G.Card" : "type_G"
"G.k : List" --> "TG_G.List" : "type_G"
"G.y : Card" --> "TG_G.Card" : "type_G"
"TG_G.List" --> "Ecore.EClass" : "type_TG_G"
"TG_G.Card" --> "Ecore.EClass" : "type_TG_G"
"TG_G.Board" --> "Ecore.EClass" : "type_TG_G"
"Ecore.EClass" --> "Ecore.EClass" : "type_Ecore"
@enduml
