@startuml
skinparam shadowing false
hide members
hide circle
class "G.L"
class "G.C"
"G.L"-->"G.C" : "cards"
class "G'.i"
class "G'.j"
class "G'.k"
class "G'.x"
class "G'.y"
"G'.j"-->"G'.i" : "prev"
"G'.j"-->"G'.k" : "next"
"G'.j"-->"G'.x" : "e1:cards"
"G'.k"-->"G'.y" : "e2:cards"

"G.L" --> "G'.j" : "f"
"G.C" --> "G'.x" : "f"
@enduml
