@startuml
digraph Diagram {
  "E_G_S";
  "V_G_S";
  "E_G_C";
  "V_G_C";
  "E_G_T";
  "V_G_T";
  "E_TG_S";
  "V_TG_S";
  "TG_C_E";
  "TG_C_V";
  "TG_T_E";
  "TG_T_V";
  "E_GT'_S";
  "V_GT'_S";
  "GT'_E_C";
  "GT'_V_C";
  "GT'_E_T";
  "GT'V_T";
  "E_G_S"->"E_GT'_S" [label=" f_S_E"];
  "V_G_S"->"V_GT'_S" [label=" f_S_V"];
  "E_G_C"->"GT'_E_C" [label=" f_C_E"];
  "V_G_C"->"GT'_V_C" [label=" f_C_V"];
  "E_G_T"->"GT'_E_T" [label=" f_T_E"];
  "V_G_T"->"GT'V_T" [label=" f_T_V"];
  "E_G_S"->"E_TG_S" [label=" type_S_E"];
  "V_G_S"->"V_TG_S" [label=" type_S_V"];
  "E_G_C"->"TG_C_E" [label=" type_C_E"];
  "V_G_C"->"TG_C_V" [label=" type_C_V"];
  "E_G_T"->"TG_T_E" [label=" type_T_E"];
  "V_G_T"->"TG_T_V" [label=" type_T_V"];
  "E_GT'_S"->"E_TG_S" [label=" type'_S_E"];
  "V_GT'_S"->"V_TG_S" [label=" type'_V"];
  "GT'_E_C"->"TG_C_E" [label=" type_C_E"];
  "GT'_V_C"->"TG_C_V" [label=" type'_C_V"];
  "GT'_E_T"->"TG_T_E" [label=" type'_T_E"];
  "GT'V_T"->"TG_T_V" [label=" type'_T_V"];
  "E_G_C"->"E_G_S" [label=" sigma_E"];
  "V_G_C"->"V_G_S" [label=" sigma_V"];
  "E_G_C"->"E_G_T" [label=" tau_E"];
  "V_G_C"->"V_G_T" [label=" tau_V"];
  "TG_C_E"->"E_TG_S" [label=" sigma_TGT_E"];
  "TG_C_V"->"V_TG_S" [label=" sigma_TGT_V"];
  "TG_C_E"->"TG_T_E" [label=" tau_TGT_E"];
  "TG_C_V"->"TG_T_V" [label=" tau_TGT_V"];
  "GT'_E_C"->"E_GT'_S" [label=" GT'_sigma_E"];
  "GT'_V_C"->"V_GT'_S" [label=" GT'_sigma_V"];
  "GT'_E_C"->"GT'_E_T" [label=" GT'_tau_E"];
  "GT'_V_C"->"GT'V_T" [label=" GT'_tau_V"];
  "E_G_S"->"V_G_S" [label=" s_G_S"];
  "E_G_S"->"V_G_S" [label=" t_G_S"];
  "E_G_C"->"V_G_C" [label=" s_G_C"];
  "E_G_C"->"V_G_C" [label=" t_G_C"];
  "E_G_T"->"V_G_T" [label=" s_G_T"];
  "E_G_T"->"V_G_T" [label=" t_G_T"];
  "E_TG_S"->"V_TG_S" [label=" s_TG_S"];
  "E_TG_S"->"V_TG_S" [label=" t_TG_S"];
  "TG_C_E"->"TG_C_V" [label=" s_TG_C"];
  "TG_C_E"->"TG_C_V" [label=" t_TG_C"];
  "TG_T_E"->"TG_T_V" [label=" s_TG_T"];
  "TG_T_E"->"TG_T_V" [label=" t_TG_T"];
  "E_GT'_S"->"V_GT'_S" [label=" s_GT'_S"];
  "E_GT'_S"->"V_GT'_S" [label=" t_GT'_S"];
  "GT'_E_C"->"GT'_V_C" [label=" GT'_s_C"];
  "GT'_E_C"->"GT'_V_C" [label=" GT'_t_C"];
  "GT'_E_T"->"GT'V_T" [label=" GT'_s_T"];
  "GT'_E_T"->"GT'V_T" [label=" GT'_t_T"];
}
@enduml
